class RoleDefinition {
  final String key;
  final String name;
  final String icon;
  final List<DynamicField> fields;

  RoleDefinition({
    required this.key,
    required this.name,
    required this.icon,
    this.fields = const [],
  });
}

class DynamicField {
  final String id;
  final String label;
  final String type; // 'text', 'select', 'number'
  final String? placeholder;
  final List<String>? options;

  DynamicField({
    required this.id,
    required this.label,
    required this.type,
    this.placeholder,
    this.options,
  });
}

final List<RoleDefinition> appRoles = [
  RoleDefinition(
    key: 'pro-boxer',
    name: 'Boxeador Profesional',
    icon: '🥊',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'nickname',
        label: 'Apodo (ej. El Chino)',
        type: 'text',
        placeholder: 'Cómo te conocen en el ring',
      ),
      DynamicField(
        id: 'weightClass',
        label: 'Categoría de Peso',
        type: 'text',
        placeholder: 'Welter (66.7kg)',
      ),
      DynamicField(
        id: 'height',
        label: 'Altura (cm)',
        type: 'text',
        placeholder: '175',
      ),
      DynamicField(
        id: 'reach',
        label: 'Alcance (cm)',
        type: 'text',
        placeholder: '180',
      ),
      DynamicField(
        id: 'record',
        label: 'Récord (W-L-D)',
        type: 'text',
        placeholder: '10-0-0',
      ),
      DynamicField(
        id: 'kos',
        label: 'KOs (Nocauts)',
        type: 'text',
        placeholder: '5',
      ),
      DynamicField(
        id: 'stance',
        label: 'Guardia',
        type: 'select',
        options: ['Ortodoxo', 'Zurdo'],
      ),
      DynamicField(id: 'age', label: 'Edad', type: 'text', placeholder: '25'),
      DynamicField(
        id: 'currentLocation',
        label: 'Ciudad de Residencia',
        type: 'text',
        placeholder: 'Buenos Aires, México DF...',
      ),
      DynamicField(
        id: 'boxrecUrl',
        label: 'URL de BoxRec (Opcional)',
        type: 'text',
        placeholder: 'https://boxrec.com/en/boxer/...',
      ),
      DynamicField(
        id: 'initialTrainer',
        label: 'Entrenador Principal',
        type: 'text',
        placeholder: 'Nombre del Entrenador',
      ),
      DynamicField(
        id: 'initialSponsor',
        label: 'Sponsor Principal',
        type: 'text',
        placeholder: 'Marca o Patrocinador',
      ),
    ],
  ),
  RoleDefinition(
    key: 'amateur-boxer',
    name: 'Boxeador Amateur',
    icon: '🥇',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(id: 'age', label: 'Edad', type: 'text', placeholder: '25'),
      DynamicField(
        id: 'weightClass',
        label: 'Categoría de Peso',
        type: 'text',
        placeholder: '69kg',
      ),
      DynamicField(
        id: 'height',
        label: 'Altura (cm)',
        type: 'text',
        placeholder: '175',
      ),
      DynamicField(
        id: 'reach',
        label: 'Alcance (cm)',
        type: 'text',
        placeholder: '180',
      ),
      DynamicField(
        id: 'stance',
        label: 'Guardia',
        type: 'select',
        options: ['Ortodoxo', 'Zurdo'],
      ),
      DynamicField(
        id: 'fights',
        label: 'Peleas disputadas / Récord',
        type: 'text',
        placeholder: '15-2-0',
      ),
      DynamicField(
        id: 'gym',
        label: 'Gimnasio / Club',
        type: 'text',
        placeholder: 'Nombre del gimnasio',
      ),
      DynamicField(
        id: 'initialTrainer',
        label: 'Entrenador Principal',
        type: 'text',
        placeholder: 'Nombre del Entrenador',
      ),
    ],
  ),
  RoleDefinition(
    key: 'cadet',
    name: 'Cadete / Semillero',
    icon: '👦',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(id: 'age', label: 'Edad', type: 'number', placeholder: '14'),
      DynamicField(
        id: 'weightClass',
        label: 'Categoría / Peso',
        type: 'text',
        placeholder: '52kg',
      ),
      DynamicField(
        id: 'height',
        label: 'Altura (cm)',
        type: 'text',
        placeholder: '155',
      ),
      DynamicField(
        id: 'reach',
        label: 'Alcance (cm)',
        type: 'text',
        placeholder: '160',
      ),
      DynamicField(
        id: 'stance',
        label: 'Guardia',
        type: 'select',
        options: ['Ortodoxo', 'Zurdo'],
      ),
      DynamicField(
        id: 'gym',
        label: 'Gimnasio / Escuela',
        type: 'text',
        placeholder: 'Escuela Municipal...',
      ),
      DynamicField(
        id: 'fights',
        label: 'Peleas / Exhibiciones',
        type: 'text',
        placeholder: '5 (Sin decisión)',
      ),
      DynamicField(
        id: 'boxrecUrl',
        label: 'URL de BoxRec (Opcional)',
        type: 'text',
        placeholder: 'https://boxrec.com/en/boxer/...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'retired-boxer',
    name: 'Boxeador Retirado',
    icon: '🕰️',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(id: 'age', label: 'Edad', type: 'text', placeholder: '45'),
      DynamicField(
        id: 'weightClass',
        label: 'Última Categoría',
        type: 'text',
        placeholder: 'Mediano',
      ),
      DynamicField(
        id: 'height',
        label: 'Altura (cm)',
        type: 'text',
        placeholder: '175',
      ),
      DynamicField(
        id: 'reach',
        label: 'Alcance (cm)',
        type: 'text',
        placeholder: '180',
      ),
      DynamicField(
        id: 'stance',
        label: 'Guardia',
        type: 'select',
        options: ['Ortodoxo', 'Zurdo'],
      ),
      DynamicField(
        id: 'record',
        label: 'Récord Final',
        type: 'text',
        placeholder: '30-5-2',
      ),
      DynamicField(
        id: 'boxrecUrl',
        label: 'URL de BoxRec (Opcional)',
        type: 'text',
        placeholder: 'https://boxrec.com/en/boxer/...',
      ),
      DynamicField(
        id: 'achievements',
        label: 'Títulos Ganados',
        type: 'text',
        placeholder: 'Campeón Mundial WBC...',
      ),
      DynamicField(
        id: 'yearsActive',
        label: 'Años Activo',
        type: 'text',
        placeholder: '1995-2010',
      ),
    ],
  ),
  RoleDefinition(
    key: 'legend-boxer',
    name: 'Boxeador Leyenda',
    icon: '🏆',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(id: 'age', label: 'Edad', type: 'text', placeholder: '60'),
      DynamicField(
        id: 'weightClass',
        label: 'Categoría Histórica',
        type: 'text',
        placeholder: 'Pesado',
      ),
      DynamicField(
        id: 'height',
        label: 'Altura (cm)',
        type: 'text',
        placeholder: '188',
      ),
      DynamicField(
        id: 'reach',
        label: 'Alcance (cm)',
        type: 'text',
        placeholder: '195',
      ),
      DynamicField(
        id: 'stance',
        label: 'Guardia',
        type: 'select',
        options: ['Ortodoxo', 'Zurdo'],
      ),
      DynamicField(
        id: 'record',
        label: 'Récord Histórico',
        type: 'text',
        placeholder: '50-0-0',
      ),
      DynamicField(
        id: 'boxrecUrl',
        label: 'URL de BoxRec (Opcional)',
        type: 'text',
        placeholder: 'https://boxrec.com/en/boxer/...',
      ),
      DynamicField(
        id: 'achievements',
        label: 'Legado / Títulos',
        type: 'text',
        placeholder: 'Hall of Fame 2020...',
      ),
      DynamicField(
        id: 'greatestFight',
        label: 'Pelea Más Importante',
        type: 'text',
        placeholder: 'vs Rival Histórico',
      ),
    ],
  ),
  RoleDefinition(
    key: 'coach',
    name: 'Entrenador / Técnico',
    icon: '🧢',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'gym',
        label: 'Gimnasio Principal',
        type: 'text',
        placeholder: 'Nombre del gimnasio',
      ),
      DynamicField(
        id: 'coachRanks',
        label: 'Rango / Nivel',
        type: 'chips',
        options: ['Provincial', 'Nacional', 'Internacional'],
      ),
      DynamicField(
        id: 'coachSpecialties',
        label: 'Público Objetivo',
        type: 'chips',
        options: ['Pro', 'Amateur', 'Cadete', 'Recreativo', 'Particulares'],
      ),
      DynamicField(
        id: 'coach_module_FORMACIÓN_TÉCNICA',
        label: 'Formación Técnica',
        type: 'chips',
        options: [
          'Enseñanza de técnica básica',
          'Corrección de golpes',
          'Combinaciones ofensivas',
          'Coordinación mano-ojo',
          'Precisión de golpeo',
          'Uso de la distancia y timing',
        ],
      ),
      DynamicField(
        id: 'coach_module_DEFENSA',
        label: 'Módulo: Defensa',
        type: 'chips',
        options: [
          'Esquives',
          'Bloqueos y paradas',
          'Defensa activa y pasiva',
          'Salidas laterales',
          'Pivoteos y cambios de ángulo',
        ],
      ),
      DynamicField(
        id: 'coach_module_PLANIFICACIÓN_TÉCNICA',
        label: 'Planificación Técnica',
        type: 'chips',
        options: [
          'Diseño de rutinas técnicas',
          'Planificación por nivel',
          'Corrección de vicios técnicos',
          'Desarrollo progresivo',
          'Ajustes técnicos según estilo',
        ],
      ),
      DynamicField(
        id: 'coach_module_TRABAJO_EN_RING_/_SPARRING',
        label: 'Trabajo en Ring / Sparring',
        type: 'chips',
        options: [
          'Supervisión de sparring',
          'Correcciones en tiempo real',
          'Control de intensidad',
          'Selección de sparrings',
          'Evaluación de desempeño',
        ],
      ),
      DynamicField(
        id: 'coach_module_ESTRATEGIA_Y_TÁCTICA',
        label: 'Estrategia y Táctica',
        type: 'chips',
        options: [
          'Análisis de rivales',
          'Diseño de plan de pelea',
          'Adaptación estratégica',
          'Estilo: Estilista',
          'Estilo: Fajador',
          'Estilo: Contragolpeador',
          'Estilo: Presionador',
        ],
      ),
      DynamicField(
        id: 'coach_module_COMPETENCIA',
        label: 'Módulo: Competencia',
        type: 'chips',
        options: [
          'Acompañamiento a eventos',
          'Trabajo en esquina',
          'Indicaciones entre rounds',
          'Lectura de combate en vivo',
          'Ajustes tácticos durante pelea',
        ],
      ),
    ],
  ),
  RoleDefinition(
    key: 'physical-trainer',
    name: 'Preparador Físico',
    icon: '🏋️',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'license',
        label: 'Certificación / Título',
        type: 'text',
        placeholder: 'Lic. en Alto Rendimiento...',
      ),
      DynamicField(
        id: 'experience',
        label: 'Años de Experiencia',
        type: 'number',
        placeholder: '5',
      ),
    ],
  ),
  RoleDefinition(
    key: 'cutman',
    name: 'Cutman',
    icon: '🩹',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'license',
        label: 'Nº Licencia / Asociación',
        type: 'text',
        placeholder: 'Certificación Internacional...',
      ),
      DynamicField(
        id: 'experience',
        label: 'Años de Experiencia',
        type: 'number',
        placeholder: '10',
      ),
    ],
  ),
  RoleDefinition(
    key: 'medic',
    name: 'Médico Deportivo / Deportólogo',
    icon: '🩺',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'license',
        label: 'Nº Matrícula Médica',
        type: 'text',
        placeholder: 'MN 12345...',
      ),
      DynamicField(
        id: 'med_specs',
        label: 'Especialidades',
        type: 'chips',
        options: [
          'Deportología',
          'Traumatología',
          'Cardiología Deportiva',
          'Emergentología',
          'Medicina General',
          'Neurología Deportiva',
          'Rehabilitación',
        ],
      ),
      DynamicField(
        id: 'med_services',
        label: 'Servicios Disponibles',
        type: 'chips',
        options: [
          'Aptos físicos deportivos',
          'Evaluación pre-competencia',
          'Control de corte de peso',
          'Tratamiento de lesiones',
          'Estudios clínicos',
          'Certificados médicos',
          'Seguimiento de campamento',
          'Control cardiovascular',
          'Evaluación post-KO',
        ],
      ),
      DynamicField(
        id: 'med_module_EVALUACIÓN_MÉDICA',
        label: 'Módulo: Evaluación Médica',
        type: 'chips',
        options: [
          'Historia clínica deportiva',
          'Evaluación médica integral',
          'Aptos físicos (Amateur / Pro)',
          'Exámenes pre-competencia',
          'Certificados médicos oficiales',
        ],
      ),
      DynamicField(
        id: 'med_module_EVALUACIÓN_CARDIOVASCULAR',
        label: 'Módulo: Evaluación Cardiovascular',
        type: 'chips',
        options: [
          'Electrocardiograma (ECG)',
          'Pruebas de esfuerzo',
          'Control de frecuencia cardíaca',
          'Detección de riesgos cardíacos',
          'Seguimiento de salud cardiovascular',
        ],
      ),
      DynamicField(
        id: 'med_module_DIAGNÓSTICO_DE_LESIONES',
        label: 'Módulo: Diagnóstico de Lesiones',
        type: 'chips',
        options: [
          'Evaluación de lesiones musculares',
          'Lesiones articulares',
          'Traumatismos por impacto',
          'Sospecha de fracturas',
          'Lesiones por sobreentrenamiento',
        ],
      ),
      DynamicField(
        id: 'med_module_TRATAMIENTO_MÉDICO',
        label: 'Módulo: Tratamiento Médico',
        type: 'chips',
        options: [
          'Indicaciones de reposo deportivo',
          'Protocolos de recuperación',
          'Antiinflamatorios / Analgésicos',
          'Infiltraciones controladas',
          'Seguimiento evolutivo de lesiones',
        ],
      ),
      DynamicField(
        id: 'med_module_CONTROL_DE_PESO_Y_CORTE',
        label: 'Módulo: Control de Peso y Corte',
        type: 'chips',
        options: [
          'Supervisión médica del corte de peso',
          'Evaluación de hidratación',
          'Riesgos de deshidratación',
          'Recuperación post-pesaje',
          'Prevención de colapsos físicos',
        ],
      ),
      DynamicField(
        id: 'med_module_ESTUDIOS_Y_CONTROLES_CLÍNICOS',
        label: 'Módulo: Estudios y Controles Clínicos',
        type: 'chips',
        options: [
          'Análisis de sangre',
          'Perfil hormonal',
          'Niveles de hierro / Ferritina',
          'Fatiga crónica',
          'Déficits nutricionales',
        ],
      ),
      DynamicField(
        id: 'med_module_FARMACOLOGÍA_DEPORTIVA',
        label: 'Módulo: Farmacología Deportiva',
        type: 'chips',
        options: [
          'Prescripción de medicación',
          'Suplementación médica indicada',
          'Control de sustancias permitidas',
          'Prevención de dopaje accidental',
          'Certificados TUE (Uso terapéutico)',
        ],
      ),
      DynamicField(
        id: 'med_module_SALUD_NEUROLÓGICA_BÁSICA',
        label: 'Módulo: Salud Neurológica Básica',
        type: 'chips',
        options: [
          'Evaluación post-conmoción',
          'Protocolos de KO / TKO',
          'Reposo neurológico',
          'Seguimiento tras golpes reiterados',
          'Derivación a neurología',
        ],
      ),
      DynamicField(
        id: 'med_module_SEGUIMIENTO_DEL_DEPORTISTA',
        label: 'Módulo: Seguimiento del Deportista',
        type: 'chips',
        options: [
          'Controles periódicos',
          'Evolución física general',
          'Aptitud para volver a competir',
          'Prevención de riesgos médicos',
        ],
      ),
      DynamicField(
        id: 'company',
        label: 'Hospital / Centro Médico',
        type: 'text',
        placeholder: 'Clínica de Alto Rendimiento...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'nutritionist',
    name: 'Nutricionista Deportivo',
    icon: '🥗',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'license',
        label: 'Nº Matrícula Profesional',
        type: 'text',
        placeholder: 'MN 6789...',
      ),
      DynamicField(
        id: 'nut_specs',
        label: 'Especialidades',
        type: 'chips',
        options: [
          'Deportes de combate',
          'Corte de peso',
          'Alto rendimiento',
          'Amateur',
          'Profesional',
          'Reeducación alimentaria',
          'Suplementación deportiva',
        ],
      ),
      DynamicField(
        id: 'nut_services',
        label: 'Servicios Disponibles',
        type: 'chips',
        options: [
          'Plan nutricional personalizado',
          'Corte de peso',
          'Hidratación deportiva',
          'Plan pre-competencia',
          'Plan post-competencia',
          'Suplementación deportiva',
          'Evaluación antropométrica',
          'Seguimiento de campamento',
          'Educación alimentaria',
        ],
      ),
      DynamicField(
        id: 'nut_module_PLANIFICACIÓN_NUTRICIONAL',
        label: 'Módulo: Planificación Nutricional',
        type: 'chips',
        options: [
          'Doc: Plan alimenticio personalizado',
          'Alimentación según categoría de peso',
          'Ajustes por etapa de entrenamiento',
          'Nutrición para campamentos de pelea',
          'Planes para Amateur / Profesional',
        ],
      ),
      DynamicField(
        id: 'nut_module_CORTE_DE_PESO_NUTRICIONAL',
        label: 'Módulo: Corte de Peso Nutricional',
        type: 'chips',
        options: [
          'Estrategias de descenso de peso',
          'Planificación progresiva de corte',
          'Reducción de grasa sin perder rendimiento',
          'Manejo de sodio y líquidos',
          'Prevención de cortes extremos peligrosos',
        ],
      ),
      DynamicField(
        id: 'nut_module_HIDRATACIÓN_DEPORTIVA',
        label: 'Módulo: Hidratación Deportiva',
        type: 'chips',
        options: [
          'Protocolos de hidratación diaria',
          'Hidratación en campamento',
          'Estrategias pre-pesaje',
          'Rehidratación post-pesaje',
          'Balance electrolítico',
        ],
      ),
      DynamicField(
        id: 'nut_module_ALIMENTACIÓN_PRE/POST_COMBATE',
        label: 'Módulo: Alimentación Pre/Post Combate',
        type: 'chips',
        options: [
          'Pre: Cargas de glucógeno',
          'Pre: Timing de comidas y digestibilidad',
          'Post: Recuperación muscular y reposición',
          'Post: Ventana anabólica y reparación',
        ],
      ),
      DynamicField(
        id: 'nut_module_SUPLEMENTACIÓN_DEPORTIVA',
        label: 'Módulo: Suplementación Deportiva',
        type: 'chips',
        options: [
          'Proteínas y Creatina',
          'BCAA / Aminoácidos',
          'Electrolitos y Vitaminas',
          'Control de sustancias permitidas (Antidopaje)',
        ],
      ),
      DynamicField(
        id: 'nut_module_EVALUACIÓN_ANTROPOMÉTRICA',
        label: 'Módulo: Evaluación Antropométrica',
        type: 'chips',
        options: [
          'Estudio de % de grasa y masa muscular',
          'Medición de pliegues cutáneos',
          'Evolución física nutricional',
          'Control de peso corporal periódico',
        ],
      ),
      DynamicField(
        id: 'nut_module_EDUCACIÓN_ALIMENTARIA',
        label: 'Módulo: Educación Alimentaria',
        type: 'chips',
        options: [
          'Hábitos saludables y organización',
          'Lectura de etiquetas nutricionales',
          'Alimentación fuera de campamento',
          'Conducta nutricional del deportista',
        ],
      ),
    ],
  ),
  RoleDefinition(
    key: 'psychologist',
    name: 'Psicólogo Deportivo',
    icon: '🧠',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'license',
        label: 'Nº Matrícula Profesional',
        type: 'text',
        placeholder: 'MN 12345...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'manager',
    name: 'Manager / Representante',
    icon: '👔',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'company',
        label: 'Empresa / Agencia',
        type: 'text',
        placeholder: 'Nombre de la promotora o agencia...',
      ),
      DynamicField(
        id: 'license',
        label: 'Nº Licencia (Si aplica)',
        type: 'text',
        placeholder: 'Licencia oficial federativa...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'promoter',
    name: 'Promotor',
    icon: '🎟️',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'company',
        label: 'Empresa Promotora',
        type: 'text',
        placeholder: 'Nombre de la promotora...',
      ),
      DynamicField(
        id: 'license',
        label: 'Licencia de Promotor',
        type: 'text',
        placeholder: 'Nº Licencia oficial...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'journalist',
    name: 'Periodista / Prensa',
    icon: '🎤',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'company',
        label: 'Medio / Prensa',
        type: 'text',
        placeholder: 'Nombre del medio o plataforma...',
      ),
      DynamicField(
        id: 'license',
        label: 'Nº Credencial / CP',
        type: 'text',
        placeholder: 'Opcional local/internacional...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'judge',
    name: 'Oficial de Combate (Árbitro/Juez)',
    icon: '⚖️',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'official_roles',
        label: 'Roles Activos',
        type: 'chips',
        options: ['Árbitro', 'Juez', 'Supervisor'],
      ),
      DynamicField(
        id: 'official_experience_level',
        label: 'Nivel de Experiencia',
        type: 'chips',
        options: [
          'Amateur',
          'Profesional',
          'Regional',
          'Nacional',
          'Internacional',
          'Mundial',
        ],
      ),
      DynamicField(
        id: 'license',
        label: 'Licencia / Certificación',
        type: 'text',
        placeholder: 'Licencia FAB / Comisión...',
      ),
      DynamicField(
        id: 'orgs',
        label: 'Organismos / Federaciones',
        type: 'chips',
        options: ['WBC', 'WBA', 'IBF', 'WBO', 'FAB', 'Comisión Local', 'AIBA'],
      ),
      DynamicField(
        id: 'official_fights_count',
        label: 'Cantidad de Peleas Oficiales',
        type: 'text',
        placeholder: '+100',
      ),
      DynamicField(
        id: 'official_module_ESPECIALIDADES_REGLAMENTARIAS',
        label: 'Módulo: Especialidades Reglamentarias',
        type: 'chips',
        options: [
          'Conteo de protección',
          'Faltas técnicas',
          'Seguridad del boxeador',
          'Reglamento Amateur',
          'Reglamento Profesional',
          'Protocolo de conmoción',
          'Evaluación de golpes (Juez)',
          'Sistema 10-Point Must',
        ],
      ),
      DynamicField(
        id: 'official_module_SERVICIOS_DISPONIBLES',
        label: 'Servicios Disponibles',
        type: 'chips',
        options: [
          'Arbitraje Amateur',
          'Arbitraje Profesional',
          'Juez de Silla',
          'Fiscalización de Eventos',
          'Capacitación / Seminarios',
          'Exhibiciones',
        ],
      ),
    ],
  ),
  RoleDefinition(
    key: 'gym-owner',
    name: 'Dueño de Gimnasio',
    icon: '🏢',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'gym_name',
        label: 'Nombre del Gimnasio',
        type: 'text',
        placeholder: 'Gym Golden Boy...',
      ),
      DynamicField(
        id: 'gym_address',
        label: 'Dirección / Ubicación',
        type: 'text',
        placeholder: 'Calle, Ciudad, País...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'recreational',
    name: 'Recreativo / Fitness',
    icon: '🏋️‍♂️',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'gym',
        label: 'Gimnasio donde entrenas',
        type: 'text',
        placeholder: 'Club de barrio...',
      ),
      DynamicField(
        id: 'experience',
        label: 'Tiempo entrenando',
        type: 'text',
        placeholder: '6 meses...',
      ),
    ],
  ),
  RoleDefinition(
    key: 'fan',
    name: 'Aficionado / Fan',
    icon: '👤',
    fields: [
      DynamicField(
        id: 'nationality',
        label: 'País de Nacimiento',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
      DynamicField(
        id: 'represents',
        label: 'País que Representa',
        type: 'select',
        options: [
          'Argentina 🇦🇷',
          'México 🇲🇽',
          'USA 🇺🇸',
          'España 🇪🇸',
          'Cuba 🇨🇺',
          'Puerto Rico 🇵🇷',
          'Senegal 🇸🇳',
          'UK 🇬🇧',
          'Japón 🇯🇵',
        ],
      ),
    ],
  ),
  RoleDefinition(
    key: 'brand',
    name: 'Marca / Sponsor',
    icon: '🏢',
    fields: [
      DynamicField(
        id: 'company_name',
        label: 'Nombre de la Empresa',
        type: 'text',
        placeholder: 'Ej. Everlast, Rival, Gym X...',
      ),
      DynamicField(
        id: 'sector',
        label: 'Sector / Rubro',
        type: 'select',
        options: [
          'Indumentaria y Equipamiento',
          'Suplementación',
          'Gimnasio / Arena',
          'Medios / Prensa',
          'Bebidas Hidratantes',
          'Otros',
        ],
      ),
      DynamicField(
        id: 'website',
        label: 'Sitio Web / Catálogo',
        type: 'text',
        placeholder: 'https://...',
      ),
      DynamicField(
        id: 'bio',
        label: 'Sobre la Marca',
        type: 'text',
        placeholder: 'Breve descripción de lo que ofrecen...',
      ),
    ],
  ),
];
